cart/urls.py
from django.urls import path
from . import views
app_name = "cart"

urlpatterns = [
    path('', views.CartView.as_view(), name="summary"),
    path('shop/', views.ProductListView.as_view(), name='product-list'),
    path('shop/<slug>', views.ProductDetailView.as_view(), name='product-detail'),
    path('increase-quantity/<pk>/', views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path('decrease-quantity/<pk>/', views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path('remove-from-cart/<pk>/', views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('thank-you/', views.ThankYouView.as_view(), name='thank-you'),
    path('confirm-order/', views.ConfirmOrderView.as_view(), name='confirm-order'),
    path('order/<pk>/', views.OrderDetailView.as_view(), name='order-detail'),
    path('payment/stripe/', views.StripePaymentView.as_view(), name="payment-stripe"),
    path('webhooks/stripe/', views.stripe_webhook_view, name="stripe-webhook")
]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', views.HomeView.as_view(), name="home"),
    path('contact/', views.ContactView.as_view(), name="contact"),
    path('cart/', include('cart.urls', namespace="cart")),
    path('staff/', include('staff.urls', namespace="staff")),
    path('profile/', views.ProfileView.as_view(), name="profile")
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

staff/urls.py
from django.urls import path
from . import views

app_name = "staff"

urlpatterns = [
    path('', views.StaffView.as_view(), name="staff"),
    path('create/', views.ProductCreateView.as_view(), name="product-create"),
    path('products/', views.ProductListView.as_view(), name="product-list"),
    path('products/<pk>/update/', views.ProductUpdateView.as_view(), name="product-update"),
    path('products/<pk>/delete/', views.ProductDeleteView.as_view(), name="product-delete"),
]

templates/base.html
{% load static %}
{% load cart_template_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-166142937-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-166142937-3');
</script>

    <title>Portfolio - E-Commerce {% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'ecommerce/icons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'ecommerce/icons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'ecommerce/icons/favicon-16x16.png' %}">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
    <link rel="stylesheet" href="{% static 'ecommerce/fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'ecommerce/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'ecommerce/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'ecommerce/css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'ecommerce/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'ecommerce/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'ecommerce/css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'ecommerce/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'ecommerce/css/custom.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css"
          integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous"/>
</head>

<body>


    <header class="site-navbar" role="banner">
        {% include 'navbar.html' %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    <span class="alert-inner--icon"><i class="ni ni-like-2"></i></span>
                    <span class="alert-inner--text d-flex justify-content-center">{{ message }}</span>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}
    </header>

    {% block content %}
    {% endblock content %}

    {% include 'footer.html' %}


{% include 'scripts.html' %}

{% block scripts %}
{% endblock scripts %}

</body>
</html>

templates/contact.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">Home</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-black">Contact</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-7">
                <h2 class="h3 mb-3 text-black">Get in touch</h2>
            </div>
            <div class="col-md-7">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit" class="btn btn-primary btn-lg btn-block" value="Submit message" />
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/footer.html
<footer class="site-footer border-top">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <p>
                    Copyright by <a href="https://jeremygehlen.com">Jeremy Gehlen</a> &copy;
                    <script>document.write(new Date().getFullYear());</script>
                    All rights reserved | This website is a personal project made with Django</i>
                </p>
            </div>
        </div>
    </div>
</footer>

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<header class="masthead">
  <div class="container h-100">
    <div class="row h-100 align-items-center">
      <div class="col-12 text-center">
        <h1 class="display-1 font-weight-bold text-light">Welcome to Django Coffee Co</h1>
        <p class="lead text-white">A great coffee shop that doesn't really exist</p>
      </div>
    </div>
  </div>
</header>


<div class="container">
    <div class="row my-5">
      <div class="col-lg-7" data-aos="fade" data-aos-anchor-placement="top-bottom"  data-aos-duration="500">
        <img class="img-fluid rounded mb-4 mb-lg-0" src="https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80" alt="">
      </div>
      <div class="col-lg-5 d-flex flex-column justify-content-between">
      <div>
        <h1 class="font-weight-bold mb-3">Django Coffee Co</h1>
        <h3>The place for the best coffee in the world. I wish!</h3>
        <p>This is a website concept of what a coffee selling e-commerce website could look like.</p>
        <p>Feel free to browse around and give some feedback through the contact</p>
      </div>
        <a class="btn btn-info btn-sm" href="{% url 'cart:product-list' %}">See our products</a>
      </div>
    </div>
    <!-- Content Row -->
    <div class="row ">
          <div class="col-md-4 mb-5">
        <div class="card h-100">
          <div class="card-body">
          <img class="card-img-top mb-3" src="https://themeforest.img.customer.envatousercontent.com/files/180904265/djangopre.jpg?auto=compress%2Cformat&q=80&fit=crop&crop=top&max-h=8000&max-w=590&s=9625d406063207f9205a65eb7d1c6ff0" alt="">
            <h2 class="text-lead mb-3">Built with Django</h2>
            <p class="font-weight-bold mb-3"><i>Uses Of Django</i></p>
            <p class="card-text mb-3">
            <i>Django is an open-source python web framework used for rapid development, pragmatic, maintainable, clean design, and secures websites. A web application framework is a toolkit of all components need for application development.</i>
            </p>
            <p class="card-text mb-3">
            <i>The main goal of the Django framework is to allow developers to focus on components of the application that are new instead of spending time on already developed components.</i>
            </p>
              <p class="card-text mb-3">
            <i>It is fully featured than many other frameworks on the market. It takes care of a lot of hassle. involved in web development; enables users to focus on developing components needed for their application.</i>
            </p>
          </div>
          <div class="card-footer">
            <a href="https://www.djangoproject.com/" class="btn btn-info btn-sm">More Info</a>
          </div>
        </div>
      </div>
      <div class="col-md-4 mb-5">
        <div class="card h-100">
          <div class="card-body">
            <img class="card-img-top mb-3" src="https://cdn.pixabay.com/photo/2015/05/26/09/37/paypal-784404_1280.png" alt="Product Image">
            <h2 class="text-lead mb-3">Users can pay using PayPal</h2>
            <p class="font-weight-bold mb-3">
              <i>The platform that grows with you</i>
            </p>
            <p class="card-text mb-3">
            <i>PayPal Commerce Platform is a comprehensive solution designed to serve your business needs and your customers, whether you’re just getting started or already a thriving enterprise or marketplace.</i>
            </p><i>Leveraging our two-sided network, the platform lets you connect with more than 295 million PayPal customers around the world and across many platforms and marketplaces. Now you can find new markets, new channels, new high-value customers. All while giving your customers the freedom to buy how they want—nearly anywhere in the world.</i>
            </p>
          </div>
          <div class="card-footer">
            <a href="https://www.paypal.com/" class="btn btn-info btn-sm">More Info</a>
          </div>
        </div>
      </div>
      <!-- /.col-md-4 -->
      <div class="col-md-4 mb-5">
        <div class="card h-100">
          <div class="card-body">
            <img class="card-img-top mb-3" src="https://stripe.com/img/v3/home/social.png" alt="Product Image">
            <h2 class="text-lead mb-3">Users can pay using Stripe</h2>
            <p class="font-weight-bold mb-3">
              <i>A fully integrated suite of payments products</i>
            </p>
            <p class="card-text mb-3">
            <i>We bring together everything that’s required to build websites and apps that accept payments and send payouts globally.</i>
            </p>
                        <i>Stripe’s products power payments for online and in-person retailers, subscriptions businesses, software platforms and marketplaces, and everything in between.</i>
            </p>
          </div>
          <div class="card-footer">
            <a href="https://stripe.com/en-fi" class="btn btn-info btn-sm">More Info</a>
          </div>
        </div>
      </div>
      <!-- /.col-md-4 -->
    </div>
    <!-- /.row -->

  </div>
  <div class="d-none d-lg-block">
      <div class="row no-gutters mb-0">
      <div class="col-md-4">
            <img class="img-fluid" src="https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80" alt="Coffee" >
      </div>
      <div class="col-md-4">
            <img class="img-fluid" src="https://images.unsplash.com/photo-1495100497150-fe209c585f50?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1951&q=80" alt="Coffee" >
      </div>
      <div class="col-md-4">
            <img class="img-fluid" src="https://images.unsplash.com/photo-1448932284983-0c7b152eba33?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80" alt="Coffee" >
      </div>
    </div>
  </div>
  <!-- /.container -->
  
{% endblock content %}

templates/navbar.html
{% load static %}
{% load cart_template_tags %}


<nav class="navbar navbar-expand-lg navbar-light bg-dark static-top">
  <div class="container">
        <a class="navbar-brand" href="/">
          <img src="{% static 'ecommerce/images/logo.svg' %}" style="height: 60px;">
        </a>
            <a class="nav-link text-muted" href="https://github.com/JSGehlen/ecommerce/">Source code <span><i class="fab fa-github ml-2 text-muted"></i></span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="bg-dark collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav mx-auto">
        <li class="nav-item active">
          <a class="nav-link " href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'cart:product-list' %}">Shop</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'contact' %}">Contact</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="{% url 'cart:summary' %}" class="site-cart">Shopping cart
                <span><i class="fas fa-shopping-cart ml-1 text-muted"></i></span>
                <span class="text-muted count">{{ request|cart_item_count }}</span>
            </a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if request.user.is_staff %}
            <li class="nav-item d-none d-lg-block"><a class="nav-link btn btn-sm btn-outline-secondary mx-2" href="{% url 'staff:staff' %}">Staff</a></li>
        {% endif %}
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                      <a class="nav-link btn btn-sm btn-outline-secondary mx-2" href="{% url 'profile' %}"><span><i class="fas fa-user"></i></span></a>                
              </li>
              <li class="nav-item">
                      <a class="nav-link btn btn-sm btn-outline-secondary mx-2" href="{% url 'account_logout' %}"><span>Logout<i class="fas fa-sign-in-alt ml-1"></i></span></a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link btn btn-sm btn-outline-secondary mx-2" href="{% url 'account_login' %}"><span>Login<i
                        class="fas fa-sign-in-alt ml-1"></i></span></a>
              </li>
            {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/order.html
{% extends "base.html" %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
            <a class="btn btn-sm btn-info mb-4" href="{% url 'profile' %}">Back to profile</a>
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">
                            Order: #{{ order.reference_number }}
                        </h5>
                        <h6 class="card-subtitle mb-2 text-muted">Ordered on {{ order.ordered_date }}</h6>
                        <div class="site-blocks-table">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Product</th>
                                        <th>Total</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in order.items.all %}
                                        <tr>
                                            <td>{{ item.size.name }} {{ item.colour.name }} of {{ item.product.title }} x {{ item.quantity }}</td>
                                            <td>{{ item.get_total_item_price }} €</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/profile.html
{% extends "base.html" %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
            <h2 class="text-black">Your profile</h2>
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">
                            Signed in as {{ request.user.email }}
                        </h5>
                        <hr />
                        <h5 class="card-title">Your orders</h5>
                        <div class="site-blocks-table">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Reference No.</th>
                                        <th>Date</th>
                                        <th>Amount</th>
                                        <th>Payment Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for order in orders %}
                                        <tr>
                                            <td><a class="btn btn-sm btn-outline-success" href="{% url 'cart:order-detail' order.pk %}"># {{ order.reference_number }}</a></td>
                                            <td>{{ order.ordered_date }}</td>
                                            <td>{{ order.get_total }} €</td>
                                            <td>{% if order.ordered %}
                                            Paid
                                            {% else %}
                                            Not Paid
                                            {% endif %}</td>
                                        </tr>
                                        {% empty %}
                                        <tr>
                                            <td colspan="4">You haven't made any orders</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/scripts.html
{% load static %}

<script src="{% static 'ecommerce/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'ecommerce/js/jquery-ui.js' %}"></script>
<script src="{% static 'ecommerce/js/popper.min.js' %}"></script>
<script src="{% static 'ecommerce/js/bootstrap.min.js' %}"></script>
<script src="{% static 'ecommerce/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'ecommerce/js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'ecommerce/js/aos.js' %}"></script>
<script src="{% static 'ecommerce/js/main.js' %}"></script>